
-define(NS_PLAYERINFO, <<"game:iq:playerinfo">>).
-define(NS_ACTIVEGAME, <<"game:iq:activegame">>).
-define(NS_PLAY_ONLINE, <<"game:iq:playonline">>).
-define(NS_GAME_INFO, <<"game:iq:gameinfo">>).
-define(NS_GAME_PLAYERTURN, <<"game:iq:playerturn">>).
-define(NS_PLAYER_DICE_ROLL, <<"game:iq:playerdiceroll">>).
-define(NS_PLAYER_PAWN_MOVE, <<"game:iq:playerpawnmove">>).
-define(NS_GAME_RESULT, <<"game:iq:gameresult">>).
-define(NS_QUIT_GAME, <<"game:iq:quitgame">>).
-define(NS_JOIN_ACTIVE_GAME, <<"game:iq:joinactivegame">>).
-define(NS_DEVICE_TOKEN, <<"game:iq:devicetoken">>).
-define(NS_PLAYER_COLLISION, <<"game:iq:playercollision">>).
-define(NS_UPDATE_CHIPS, <<"game:iq:updatechips">>).
-define(NS_PLAYER_SAME_CELL, <<"game:iq:playersamecell">>).
-define(NEW_START_SESSION, <<"urn:ietf:params:xml:ns:xmpp-session">>).
